package com.github.maxopoly.banrod.model;

public enum BanEffect {

	NOTHING, ACCOUNT_BAN, CREATE_ACCOUNT_BAN, CLUSTER_BAN, CREATE_CLUSTER_BAN, CREATE_CUSTOM1, CUSTOM_1, CREATE_CUSTOM2, CUSTOM_2, CREATE_CUSTOM3, CUSTOM_3, CREATE_CUSTOM4, CUSTOM_4, CREATE_CUSTOM5, CUSTOM_5;
	
}
